lib/SequelizeResolver.ts
lib/api/services/SequelizeService.ts
lib/api/services/index.ts
package-lock.json
package.json
test/fixtures/app.js
test/index.js
test/unit/lib/transformer.test.js
test/unit/lib/validator.test.js
test/unit/services/SequelizeService.test.js

Updates Dependency, adds some convince helpers in app.services.SequelizeService

[chore] update dependencies, add utils

---

lib/SequelizeResolver.ts
lib/api/services/TapestryService.ts
package-lock.json
package.json
test/integrations/spool.test.js

Exposes sequelize to the model, aliased by "model.datastore"

[feat] expose the datastore to the model

---

lib/transformer.ts
package-lock.json
package.json

Throws error if missing resolver.connect or if resolver is not of a SequelizeResolver Instance

[feat] throw error if misconfigured resolver

---

lib/SequelizeResolver.ts
package-lock.json
package.json

[fix] findOne

---

lib/errors/ModelError.ts
package-lock.json
package.json

Model Error Status Codes
- resolves #???

[feat] ModelError status codes

---

lib/errors/ModelError.ts
lib/index.ts
lib/utils.ts
package-lock.json
package.json
test/unit/lib/utils.test.js

[feat] merge

---

lib/utils.ts
package-lock.json
package.json
test/fixtures/app.js
test/fixtures/testmodel2.js
test/integrations/spool.test.js

Test Model Extending
- resolves #???

[chore] test model extending

---

lib/SequelizeResolver.ts
package-lock.json
package.json
test/integrations/spool.test.js

Adds Build unit tests that takes 2 arguments and persists instances with associations.  
- resolves #12

[fix] fixes #12

---

lib/transformer.ts
package-lock.json
package.json

Uses the Fabrix logger for Sequelize
- resolves None

[feat] use fabrix log for sequelize

---

lib/transformer.ts
package-lock.json
package.json

logging should be able to be turned off

[fix] logging should be able to be turned off

---

lib/config/models.ts
lib/config/spool.ts

[chore] update docs

---

package-lock.json
package.json
test/unit/lib/SequelizeSpool.test.js

[chore] LTS

---

CHANGELOG.md
README.md
package-lock.json
package.json

[feat] update deps

---

lib/api/services/SequelizeService.ts
test/unit/services/SequelizeService.test.js

- added tests that fail for previous version
- modified mergeOptionIncludes
Fix bug related to #19
- resolves #19

#19 fixed bug when you have multiple items in includes array

---

lib/SequelizeSpool.ts
lib/schemas.ts
lib/validator.ts
package-lock.json
package.json

Adds tests to find models config and validate it.
- resolves #26

[fix] fixes #26 error not being thrown

---

lib/SequelizeSpool.ts

Improved the validation check
- resolves #26

fix: validation check for the models config file

---

lib/api/services/SequelizeService.ts
package-lock.json
package.json

Fixes merge-options not being included in spool deps

[fix] deps, merge-options

---

lib/SequelizeResolver.ts
lib/transformer.ts
package-lock.json
package.json
test/fixtures/app.js
test/fixtures/testmodel3.js
test/unit/lib/transformer.test.js

allows removal of generated attributes in an easy to configure way.

[feat] removeAttributes

---

package-lock.json
package.json

Locks down Sequelize 4 until 5 is actually ready.

[feat] lock down to stable version of Sequelize 4

---

lib/SequelizeResolver.ts
package-lock.json
package.json
test/integrations/spool.test.js

Fixes grabbing the schema of the model from the resolver.
- resolves #???

[fix] schema on resolver

---

lib/transformer.ts
package-lock.json
package.json

[feat] allow heavy modification of Sequelize

---

lib/SequelizeResolver.ts
lib/transformer.ts
package-lock.json
package.json
test/fixtures/app.js
test/fixtures/testmodelExtend.js
test/fixtures/testmodelExtend2.js
test/integrations/spool.test.js

Extend prototype of parent model when model extends another model

[feat] parent proto extension

---

lib/SequelizeResolver.ts
lib/SequelizeSpool.ts
lib/transformer.ts
package-lock.json
package.json
test/fixtures/testPlugin2.js
test/integrations/spool.test.js
test/unit/lib/transformer.test.js

[feat] fix local and global namespaces #43

---

lib/SequelizeSpool.ts
lib/api/services/SequelizeService.ts
lib/transformer.ts
lib/tsconfig.json
lib/validator.ts
package-lock.json
package.json
test/fixtures/app.js

- This was a lingering issue, and is now fixed.
A model can select the store by defining it in the model's config, the config.models.ModelName.store, and by conifg.models.defaultStore in that order.

feat(models): Select Store by model config

---

lib/SequelizeSpool.ts
lib/api/services/TapestryService.ts
lib/config/errors.ts
lib/config/index.ts
lib/errors/ModelError.ts
package-lock.json
package.json
test/fixtures/app.js
test/unit/lib/SequelizeSpool.test.js

feat(): adopt spool-errors

---

lib/errors/ModelError.ts
lib/transformer.ts
package-lock.json
package.json
test/fixtures/app.js
test/unit/lib/errors.test.js
test/unit/lib/sequelize.callbacks.test.js
test/unit/lib/transformer.test.js
test/unit/lib/utils.test.js
test/unit/services/SequelizeService.test.js
test/unit/services/TapestryService.test.js

Add tests for sequelize replication
- resolves #49

Migrating test to non deprecated method
